version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pillow -t .
      - pip install boto3 -t .
  
  build:
    commands:
      # Lambda deployment
      - echo "Zipping and deploying Lambda code..."
      - zip -r function.zip lambda_function.py
      - aws lambda update-function-code --function-name ProcessImageFunction --zip-file fileb://function.zip --region ap-southeast-2
      
      # Web files deployment to EC2
      - echo "Deploying web files to EC2..."
      - aws ssm send-command \
          --targets Key=tag:Name,Values=YourEC2Name \
          --document-name "AWS-RunShellScript" \
          --parameters commands=["sudo aws s3 cp s3://s3-lambda-1735992190/web/upload.html /var/www/html/",
                               "sudo aws s3 cp s3://s3-lambda-1735992190/web/success.html /var/www/html/"]

artifacts:
  files:
    - function.zip
    - web/*
  discard-paths: no
